### ISSUE TITLE
Inquiry about the RT60

### ISSUE THREAD

**Issue by SaoYear** [Chutlhu/dEchorate#38]
Hi, 

Thanks for sharing the codes and the dataset!

I have some quesions on using the dataset:

1. Can I use the `acu_utils.py` file to obtain the RT60 of each RIR? 
If the answer is yes, which function, `rt60_from_rirs` or `rt60_with_sabine`, shall I use.

2. In the paper section 3, you mentioned that there are two sets are created (set A and B), and only set A is used for estimation of RT60. I am wondering if the annotation of set A and B are also provided in this repo?

3. Is there any annotation of fullband rt60 for each (room of) rir(s) in the dataset?

Thanks in advance!

**Comment by Chutlhu** [comment]
Hello, thank you for your interest in our work.
Let me come back to you shortly, as I need to remember what we did :)

**Comment by Chutlhu** [comment]
Hello, sorry for the late reply.
Questions n. 1 and 2:
In the end, the RT60s were estimated and inspected "manually" by colleague C. Foy (it is related to this [article](https://pubs.aip.org/asa/jasa/article/150/2/1286/615382)) because in very-echoic case we have "multi-slope" scenario and freq-dependent RT60 (due to real acoustic conditions).
Notice that these scripts were adapted from pyroomacoustics routine for [rt60 estimation](https://pyroomacoustics.readthedocs.io/en/pypi-release/pyroomacoustics.experimental.rt60.html#module-pyroomacoustics.experimental.rt60).

Question 3:
We provide the band-wise annotation in the paper. I should update the database with this info.
At the time of the recording, I didn't have the equipment for measuring the RT60.

I hope this helps, let me know

**Comment by SaoYear** [comment]
We also found the multi-slope cases when measuring the T60 manually.
I would just average the provided band-width values as a rough reference of full-band T60.

Many thanks for your responses!
